// The emojis in folderEmojis are compatible with Noto Emoji font's monochrome
const folderEmojis = {
  GENERAL: "📁",
  DOCUMENT: "📄",
  IMAGE: "📸",
  AUDIO: "🎧",
  VIDEO: "🎬",
  ARCHIVE: "🗃",
  TRASH: "🗑",
  ART: "🎨",
  BACKUP: "💾",
  BOOK: "📚",
  DRAFT: "✍",
  EVENT: "🎂",
  FAMILY: "👪",
  FAVORITE: "⭐",
  FINANCE: "💰",
  FITNESS: "🏃",
  GAMING: "🕹",
  HUMOR: "😂",
  IDEA: "💡",
  LEARNING: "🧠",
  LIST: "📋",
  PERSONAL: "🤍",
  PROGRAMMING: "💻",
  PROJECT: "🚧",
  PUZZLE: "🧩",
  RECEIPT: "🧾",
  RECIPE: "🍲",
  RPG: "🗡",
  SCHOOL: "🎓",
  VACATION: "⛱",
  WORK: "💼",
};

// The emojis in folderEmojisDropdown are cannot be shown with Noto Emoji font's monochrome in the select element, so it's better to use the full color versions for those few that are not displaying properly in the dropdown, e.g., trash (Trash), dagger (RPGs), card file (Archives), joy stick (Gaming), heart (Favorites)
const folderEmojisDropdown = [
  { value: "GENERAL", name: "General file", image: "📁" },
  { value: "DOCUMENT", name: "Documents, reports", image: "📄" },
  { value: "IMAGE", name: "Images, pictures", image: "📸" },
  { value: "AUDIO", name: "Audio, songs, podcasts", image: "🎧" },
  { value: "VIDEO", name: "Video, movies", image: "🎬" },
  { value: "ARCHIVE", name: "Archive", image: "🗃️" },
  { value: "TRASH", name: "Trash", image: "🗑️" },
  { value: "ART", name: "Art", image: "🎨" },
  { value: "BACKUP", name: "Backup", image: "💾" },
  { value: "BOOK", name: "Books", image: "📚" },
  { value: "DRAFT", name: "Drafts", image: "✍️" },
  { value: "EVENT", name: "Events, desserts", image: "🎂" },
  { value: "FAMILY", name: "Family, friends", image: "👪" },
  { value: "FAVORITE", name: "Favorites", image: "⭐" },
  { value: "FINANCE", name: "Finances, taxes, money", image: "💰" },
  { value: "FITNESS", name: "Fitness, exercise", image: "🏃" },
  { value: "GAMING", name: "Gaming", image: "🕹️" },
  { value: "HUMOR", name: "Humor, funny", image: "😂" },
  { value: "IDEA", name: "Ideas", image: "💡" },
  { value: "LEARNING", name: "Learning, brainstorming", image: "🧠" },
  { value: "LIST", name: "Lists, to do", image: "📋" },
  { value: "PERSONAL", name: "Personal, special", image: "♥️" },
  { value: "PROGRAMMING", name: "Programming", image: "💻" },
  { value: "PROJECT", name: "Projects, work-in-progress", image: "🚧" },
  { value: "PUZZLE", name: "Puzzles", image: "🧩" },
  { value: "RECEIPT", name: "Receipts, poetry", image: "🧾" },
  { value: "RECIPE", name: "Recipes, dishes", image: "🍲" },
  { value: "RPG", name: "RPGs, swords, fantasy", image: "🗡️" },
  { value: "SCHOOL", name: "Schooling", image: "🎓" },
  { value: "VACATION", name: "Vacation, travel", image: "⛱️" },
  { value: "WORK", name: "Work, office", image: "💼" },
];

module.exports = { folderEmojis, folderEmojisDropdown};
