const folderEmojis = {
  DOCUMENT: "📄",
  IMAGE1: "📸",
  IMAGE2: "🖼",
  AUDIO1: "📻",
  AUDIO2: "🎧",
  VIDEO1: "📹",
  VIDEO2: "🎬",
  VIDEO3: "🎞",
  ARCHIVE1: "🗄",
  ARCHIVE2: "🗃",
  TRASH: "🗑",
  FOLDER1: "📁",
  FOLDER2: "📂",
  ART: "🎨️",
  BACKUP: "💾",
  BOOK: "📚",
  DRAFT: "✍️",
  EVENT: "🎂",
  FAMILY: "👪",
  FAVORITE: "⭐",
  FINANCE: "💰",
  FITNESS: "🏃",
  IDEA: "💡",
  LEARNING: "🧠",
  LIST: "📋",
  PERSONAL: "🤍",
  PROGRAMMING: "💻",
  PROJECT: "🚧",
  PUZZLE: "🧩",
  RECEIPT: "🧾",
  RECIPE: "🍲",
  SCHOOL: "🎓",
  SWORD: "🗡",
  VACATION: "🏖️",
  WORK: "💼",
};

module.exports = folderEmojis;
